### ISSUE TITLE
Update a NEW game informations

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#25]
I found a big bug this evening that stop my work. I never see it before :(
You can try on mon PI.
- I go to **ARCADE**.
- **Search New games**. It found 4 games.
- I write "**New**" in the **FILTER** input.
- I see the game, and **EDIT** the bios file **SKNS.ZIP**
- And when i want to **change the TITLE**, Webtropie **bug** a lot :(
I try to write : **Super Kaneko Nova System BIOS**
But it write me and show me an other game informations ... like if he search a game ?
And change the rom name i want to work on, i can't work on this rom and same with other NEW games :(
And same with a real game already in **gamelist.xml**

Have you a solution please ?
Thanks

**Comment by Darknior** [comment]
The only solution i found was to click **HIDE** and **SAVE**.
Then the game is on the **gamelist.xml** and i can work on it.

**Comment by Darknior** [comment]
And i see we can't **remove** a game, from the **directory** or from the **gamelist**.
It can help for the 1.0 release :p

**Comment by Darknior** [comment]
Other bug, when i edit a game i can use LEFT / RIGHT and it edit an empty game. it is bad :(
same i can't move with arrow in description because it change gamelist. I don't have this bug before.
I can't also use ENTER in description, i can't change and add new line. It really break Webtropie.

**Comment by gazpan** [comment]
hi, so sorry about left/right input problem, that should be ok now.

**Comment by Darknior** [comment]
I will try when I come back in some hours... And the ENTER and name input working like a search input?

**Comment by gazpan** [comment]
... I haven't been able to repeat that yet, the fix I did fixed it, I can over type the name and it stays on the same game, ... yes and ENTER is ok now too, in the description if I enter some text then press enter it inserts a new line.

**Comment by gazpan** [comment]
... looking forward to a 1.0 release, it will be nice to have a stable version away from development! ...

**Comment by Darknior** [comment]
- LEFT/ RIGHT / ENTER bugs are fixed.
- I always have the bug to modify NEW games :(

1. Try it on my PC : http://???.???.??.??/app/#!/amiga500
2. Click on menu **SCAN NEW GAMES**, they are shown with **Yellow color.**
3. DoubleClick on **Heimdall 2 (AGA) [HDF]**
4. Select all the title and delete it to write something other after.
5. **BUG** the game with an **EMPTY title disappear** and the **EDIT POPUP** change to **Flashback [HDF]** ??????
6. And if you close POPUP to **comeback to gamelist**, the NEW game **Heimdall has disappear** too :(

> ... looking forward to a 1.0 release, it will be nice to have a stable version away from development! ...

Yes for sure, you are near to release the 1.0 ! We have no many bugs to fix...

- Please if you open my **Dune II - The Battle for Arrakis** it is missing, only on the XML. Is it possible to write it in **RED** with **MISSING** like new games are in Yellow. Because we don't know it without open popup.
- Is it possible to have a **remove** button on **EDIT POPUP** ? With a **validate popup** to ask if we are sure and if we want also remove the **ROM FILE** on the HDD (or only the game on gamelist)

If we have these **two feature + bug free**, the v1.0 will be ready to release :D

**Comment by gazpan** [comment]
Delete name fix and added missing text and style
I haven't added the "remove" button yet

**Comment by Darknior** [comment]
For me the delete name is always not working :(
When i open Heimdall and remove it, it disappear and Webtropie put me on Flashback :(
And if i'm not delete the name and write a letter on title it save this letter if i close the popup, not save ... and i see the letter in the file list ... strange ...

Now we can see MISSING games, it can be cool to have this DELETE button from gamelist.xml,
Delete games totally from gamelist and file is interesting too.

**Comment by Darknior** [comment]
OK i have try again and i finally understand what you do but it is really strange to use lol
When i empty the Heimdall name, Webtropie change edited game to game before, and you put a new line in gamelist with an empty name.
Why can't i empty the name and continue to edit the same game ?
The game name is your EDIT ID ? Can't you use the ROM NAME nobody can change ?
Also if i rename a NEW game you save the change if i quit it without saving ...
Same for MISSING games, the only games that working fine are games from gamelist.xml

I made a video of the problem : [Video 16-01-2018 12-38-26-1.zip](https://github.com/gazpan/WebtroPie/files/1634940/Video.16-01-2018.12-38-26-1.zip)

- It works better than before and not remove the game, but it is not really user friendly :(
- If you can add the DELETTE button it will really help too.

**Comment by gazpan** [comment]
His thanks for this, I've tried to repeat the problem but don't think I have as you have described.
I've made a change so that when the name is deleted you still see the "New: " in the list which should mean that the filter will keep it in the list.... but, I haven't pushed the change yet (see my other message on Issue 8)

The previous change I did put whichever game you click on into a variable that is remembered, then, whatever happens to the list and filtering can't affect the editor, so this is what is confusing me since I can't imagine how this is still a problem - but I haven't seen your video yet so hopefully this will make me understand.

thanks again

**Comment by Darknior** [comment]
Ok cool. Tell me if the video help you or if i must make an other one.

**Comment by gazpan** [comment]
It helped, thanks a lot, I've I made a couple of changes that will make it much better

The first thing wrong was that it was showing the currently selected game's path in the editor instead of the currently edited game's path ... this was confusing.

The second thing about the list changing, when the name is blank the list now shows "New: " + ROM filename which makes it clear which one you are clicking on.

I think that saving was probably still working correctly but was confusing because of the above errors but I haven't double checked yet.

So, I want to just check I haven't created any obvious bugs, and as you say we need a delete function so I'll add this later and push the changes

ta

**Comment by Darknior** [comment]
Ok thanks a lot, i understand the errors, i think now it will be perfect :D 
I have think an video is better that a long text with bad english lol
I will stand your commit to try it ;)

**Comment by gazpan** [comment]
Hi, no, it was a good explanation again, just me not noticing some things but all should be ok now I hope.

I've committed my changes

- Fix delete new scanned game name
- EmulationStation running warning (only shows when Save Metadata on exit is set), sopt ES option for local users
- EmulationStation stop/start option under new RetroPie menu for local users
- Save game speed up, progress (pacman) spinner
- Delete game
- Video play/pause position fix
- Main menu now modal (open animation)
- slide animations fix

I was going to add a "Are you sure you want to delete..." on the delete button and maybe a checkbox or second question about deleting the rom but ran out of time tonight.
I also need to review README and update the Wiki.

I've called it 0.9 :) , there's a few things that it would be nice to try to get in before v1, what do you think below
- right click (single game or multi selected list) add to custom game list
- right click (single game or multi selected list) delete game
- show "Duplicate: " games similar to "New:", "Missing: "

.. then write a RetroPie menu to install, uninstall, start standalone + create RetroPie pull request

**Comment by Darknior** [comment]
- Fix when removed new scanned game name : WORKING fine
- EmulationStation running warning (only shows when Save Metadata on exit is set), stop ES option for local users : WORKING, i can see it and close ES. I have made the menu translation.
- **EmulationStation stop/start option under new RetroPie menu for local users** : I can't see it anywhere, it is a big problem lol ... and i'm in local with **http://192.168.1.21/app/#!/amiga500**
- Editor 'Save' speed up, progress (pacman) spinner : WORKING fine
- **Delete game** : WORKING fine for games in gamelist MISSING or not. Not for NEW games !?
- Video play/pause position fix : WORKING fine
- Main menu now modal (open animation) - (I'm thinking of making editor modal but this would prevent helper from working in the editor so not sure) : WORKING fine. What will give us to have editor as a modal too ? I don't think it was important if it's only for animation...
- slide animations fix : WORKING fine.

- Great if you can add this question before REMOVING a game. Checkbox is the best solution, i think, already checked to remove file too.

- Good idea for the 0.9 version :)
I see it, but you not make it here : https://github.com/gazpan/WebtroPie/releases
It can be cool for users to have some stable release some time ...

For the version 1.0 : 

- right click (single game or multi selected list) add to custom game list : EXCELLENT
- right click (single game or multi selected list) delete game : EXCELLENT
- show "Duplicate: " games similar to "New:", "Missing: " : WOAW GREAT if possible !!!
- then write a RetroPie menu to install, uninstall, start standalone + create RetroPie pull request : Yes for sure ...

**Comment by gazpan** [comment]
- thanks, I will look for the translation pull request
- oh no! the startup and shutdown option should be under the  [retropie menu](192.168.1.21/app/#!/retropie) - but on the Dark Steel Theme I think that the logo obscures the first game list entry a little so you may have to click the bottom or press return ...
<img width="201" alt="darksteel" src="https://user-images.githubusercontent.com/18727686/35066766-b2c16702-fbc9-11e7-8dbc-3432df18e67f.png">
- never mind the modal editor, it was something that someone suggested a while ago in the thread but I don't think it would give any benefit
- oh, good thinking Delete shouldn't really show for a new game

I'm glad it's all mostly working now.

I agree, I'll finish the few more small changes then make a release branch on GitHub.

**Comment by gazpan** [comment]
Hi, the startup and shutdown option will be under the retropie menu http://192.168.1.21/app/#!/retropie - but Note: on the Dark Steel Theme I think that the

**Comment by Darknior** [comment]
> oh no! the startup and shutdown option should be under the retropie menu 

Oulaaaa ... ok i found it, and i know this bug on my beta skin i must fix it, thanks :)
What do you do it ? Is it easier for you ? Because it is bad to use for us. When we have many systems like me ... it is loonnngggg to find this option.
Is it really hard to add a NEW button on the BOTTOM menu ? After THEME and STYLE.

> oh, good thinking Delete shouldn't really show for a new game

I think you must show it, delete a NEW game is fine, because it can be a rom or a file we miss on our hard drive. If we can remove it from Webropie it will save us some time :)

**Comment by gazpan** [comment]
OK, yes I can easily add it to the bottom menu so I will add an option for it in the main menu so that you can choose whether to see the startup/shutdown es option on the helpbar or not.
I will do this for next time.

The reason I don't show all options for everyone always is that some themes (like Workbench) have the help bar positioned halfway across the screen or maybe the font is big so then many options tend to wrap around and it just looks messy or goes off the screen and so it doesn't work anyway, which is fine if the user chooses that but I don't think I should force the user to have all those options if it doesn't work well with their preferred theme and they don't use them all too.

So, I will add it as an optional helpbar option.

I'll keep the RetroPie menu too I think, I know there isn't much there at the moment but this is where I expect to add options and functions that are not really to do with any one system, like the dashboard for example, maybe advanced search goes on that menu or maybe an icon on the helpbar, the good thing about the menu is that space is unlimited so it's there for future options. Maybe I write it so that whatever is added to the RetroPie menu can also be shown on the helpbar if that's what the user wants ... but yes, I think startup/shutdown es is a special case.

**Comment by gazpan** [comment]
... hmmm, maybe I should just have it in the main menu, which until now is all options to do with WebtroPie options, whereas things to do with RetroPie are all in the themed system, so I would be changing it's purpose but on the other hand it's more accessible that searching through systems.

**Comment by Darknior** [comment]
> I can easily add it to the bottom menu ...
... I don't show all options for everyone always is that some themes ...
... So, I will add it as an optional helpbar option....
... I'll keep the RetroPie menu too I think...

Yes you are right, i understand, good idea :)
And keep it on the Retropie menu, i had the same idea than you lol

> add options and functions that are not really to do with any one system, like the dashboard for example, maybe advanced search ...

Yes it is a good idea for these options not used to update gamelist.
**Maybe the good idea would be to add a home button/icon on the bottom menu** :D 
With it we can in one click go to it, and Start/Stop ES, watch Dashboard informations, etc ....
And come back quickly to games with the internet explorer precedent button :)
I think it can make the trick and is enough fast to use ... BUT you must verify you fine store the new URL each time we move on Webtropie (only when it change) in History because some time it is not stored fine :(
There is a JS command for it. To work on the navigator history.
What do you think about that ?

**Comment by gazpan** [comment]
yes, good idea, there is already a heart icon to go to auto-favourites so maybe the word "home" or house icon to go to the retropie menu, and yes I can control the history so that both browser back and helpbar back returns to the previous page.

I'll add both as optional helpbar items, I'll make the favourite optional too I think to be consistent

**Comment by gazpan** [comment]
added delete confirmation + helpbar start/stop ES

I've not added the home icon yet, I started to look at 'home' svg's then thought that the retropie logo could be ok, but I'd prefer to make a compact svg instead of a big png. But then I thought that perhaps it would be better to add it later when there is more in the menu to make it worth visiting that menu ...

**Comment by Darknior** [comment]
Arg really bad i take many time to do a good french translation of the new text and you remove it, i don't save it i don't remember it :(

**Comment by Darknior** [comment]
Arg i can't find it on the history too :( ...
And you forgot your new option : 
    <string name="ShowESControl" value="Show ES Start/Stop" />
I can't try it ...

Can you fix it and maybe recover my french translation please ?

**Comment by Darknior** [comment]
I have pull your update https://github.com/gazpan/WebtroPie/pull/26#event-1432350929

And i check the bottom menu option and i can't find this menu ?
Where is this START/CLOSE ES ? Ans i try in local network.

Is it possible to add in the option menu to hide the LAUNCH button please.
Every where, in EDIT popup and BOTTOM menu. I don't use it and i'm always afraid to click it :(
Afraid too some one click it with online access because you not hide it with online access. Or maybe you do it but i can't see it because my computer always understand i'm in local network lol
Thanks

**Comment by gazpan** [comment]
Hi sorry about the Language troubles, I did miss a couple of options from American and French.

I've hidden the Edit option on the Helpbar since it's easier just to use the gamelist.

I've made Launch optional

Can you try again please?

Thanks

<img width="666" alt="helpbarmenu" src="https://user-images.githubusercontent.com/18727686/35165282-a1f99142-fd45-11e7-9a2c-81370cade71b.png">

**Comment by Darknior** [comment]
No problem lol some time we miss something lol
Yes EDIT is really not important on bottom menu.
Yes it's cool i can hide it on bottom menu, but i always see it on edit popup.

![sans titre-2](https://user-images.githubusercontent.com/3703317/35165992-a5e8439c-fd50-11e7-9d12-246fb15db3a5.jpg)

I see it on your screenshot but it always not not working for me :(

![sans titre-1](https://user-images.githubusercontent.com/3703317/35166018-b79543f6-fd50-11e7-8f02-3f4533d0f7dd.jpg)

**Comment by Darknior** [comment]
I have translate the two new options https://github.com/gazpan/WebtroPie/pull/27

**Comment by gazpan** [comment]
Thanks, that's merged and I've fixed the missing options now

**Comment by gazpan** [comment]
..oh, I've hidden Launch in the Editor now too

**Comment by Darknior** [comment]
YES all is near perfect now lol
The 0.9 version is down :)

- Maybe a little update, i have try to close and open ES and it works fine.
But i think a YES/NO popup can be cool before closing ES ... to prevent errors :p 
- When i OVER the CLOSE ES button, it is not gray like other one ... it will be better if all works same.

**Comment by gazpan** [comment]
Well spotted, I've made those changes now, yes, if you are ok with these last changes I will create a release 0.9.

**Comment by Darknior** [comment]
Yes i think the 0.9 is done now. Champagne 👍 
If miss nothing all is working fine :)
Thanks a lot

**Comment by gazpan** [comment]
OK, done, 0.9.0 is now release \o/ !!! :smiley:

Thanks again for all of your help in steering this where it needed to go, you made this happen! :thumbsup:

**Comment by gazpan** [comment]
Hi Darknior, not to make too big a thing out of it but do you want to post on RetroPie forum?, my head is blank, I don't know want to say, I'd probably just say "Released 0.9.0" !

**Comment by Darknior** [comment]
Ok no problem i will do it now ;)
I have began to write our ideas in new issues ... i try to forgot nothing...
