### ISSUE TITLE
BUG: Error in SYSTEM list !

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#46]
Hi
Please can you take a little time to fix this problem who does not help me to finish my Skin :(

When you read the **es_system.cfg** i don't understand why but you lost some systems :(
You can see it on my **Webtropie**, and verify the SYSTEM file i send you before, **6 systems are lost** : 

- **MSX** (1), **MSDOS, PC88, PC98, OpenBOR, x68000**

And some are inverted not like on the real ES : Capcom System inverted with Coleco Vision
And same with the 3 Nec consoles.

It is strange ....
I also try to rename my 3 AMIGA entry : **amiga500, amige1200, amiga-cd32**
To : **amiga1-500, amiga2-1200, amiga3-cd32**
To have the good order on System list, and they disappear too :(
And it works fine on the real ES.

- Because if i understand fine **NAME** is only a name, to order the systems. The one you must use to list sytems in Webtropie.
- **FULLNAME** is there to show if there is no logo on theme with the _LogoText_ label.
- **PATH** is where to found games files, with **EXTENSION**, you use to count games.
- **COMMAND** with **PLATFORM** is used to launch games.
- **THEME** is the name of the directory on theme to design a system. A same directory can be used to design two different systems like _Genesis/Megadrive_.  
And some _THEME directories_ can be not use on _es_system.cfg_ but created to use with future **CustomCollection** option you will add later. I don't search for the moment where ES is writing CC informations ...

**Comment by Darknior** [comment]
Thanks :)
[es_settings.zip](https://github.com/gazpan/WebtroPie/files/1735046/es_settings.zip)

I'm really looking forward to testing a fix for this bug to make changes in the naming of my systems and see what happens.
Because by default it is not super logical to separate all NINTENDO or SEGA consoles for example.

**Comment by Darknior** [comment]
Hi
I have search for this bug because it boring to work on my skin.
And i have understand and found some problems : 

- If the **gamelist.xml** start with **XML info**, Webtropie not read it !

`<?xml version="1.0"?>`

- If there is only `<gameList />` it's not working too. I must add **one game information** to make the system displayed in Webtropie

```
<gameList>
	<game>
		<path>/home/pi/RetroPie/roms/fds/Famicom Grand Prix - F1 Race (Japan).zip</path>
		<name>Famicom Grand Prix - F1 Race (Japan)</name>
	</game>
</gameList>
```

Now i have understand this, i can make Webtropie show all my systems listed in **es_settings.xml**

But there is an other bug : 

When i enter this system that i can now see, it's **empty**. I must move to an other system that working fine and **where i can see games** with LEFT / RIGHT and them when i come back, i can see the game i have add myself to the **gamelist.xml**
And it is not a user permission problem.

Then i have this problem on ScummVM, MSX, MSX2, CPC, .... and some other i try to continue.
On MSX2 i try to modify and add a game with Webtropie.
I can **modify** the first game without any problem.
The problem come with the second game, when i try to **add** it.
It record some strange informations in the gamelist.xml

```
    <index>1</index>
    <image>/home/pi/RetroPie/medias/msx2/box front/AcroJet (Cart) (Japan).jpg</image>
  </game>
  <game/>
</gameList>
```
(I remember then i've got this bug on my SNES too, two days ago, and SNES is working fine from many month.

- What is this new **<index>** tag ? it not exist in ES.
- The last `<game/>` add by Webtropie crash the list, if i remove it the list come back.

And the skin always not working fine with these systems where i add games ...
I add images and i cant see these images and text informations on Webtropie ???
You can try them on my PI if you want, for exemple MSX2.

A system with only the LOGO on the skin : 
![4](https://user-images.githubusercontent.com/3703317/36805657-4768beae-1cbe-11e8-90fb-c3ebe6d9e960.jpg)
The game list is not display fine, the menu background is not displayed.
![3](https://user-images.githubusercontent.com/3703317/36805704-6915c222-1cbe-11e8-9075-7c1c73aed8f1.jpg)
Same problem in Retropie Options you are creating. But i can see my background image, only the menu image is always missing.
![2](https://user-images.githubusercontent.com/3703317/36805767-8a08e7ac-1cbe-11e8-83ed-d3c8edaaef98.jpg)
A normal system that working fine and using same them XML files
![1](https://user-images.githubusercontent.com/3703317/36805837-aa7edd66-1cbe-11e8-99c7-f7499729afa1.jpg)
Strange ...

You can DL my theme here : https://github.com/Darknior/RVGM-ES-Theme
I have open the git but not sharing it for the moment. I want to add some more systems before ...

**Comment by Darknior** [comment]
And the game XML TAG order when i record a game is totally bad :(
You add the new lines at the end of <game>, And when i create it i think it is in order i complete it ...
Is it possible to always use the same ES order to make it easier to manage please.

 `  <game>
    <path>/home/pi/RetroPie/roms/msx2/Gradius 3 - The Eve of Destruction (Cart) (Japan).zip</path>
    <name>Gradius 3 - The Eve of Destruction (Japan)</name>
    <desc>The Bacterians' Commandant Gopher plans to assassinate little Lars XVIII and change the course of history... Block Gopher's ambition!</desc>
    <image>/home/pi/RetroPie/medias/msx2/box front/Gradius 3 - The Eve of Destruction (Cart) (Japan).jpg</image>
    <marquee>/home/pi/RetroPie/medias/msx2/logos/Gradius 3 - The Eve of Destruction (Cart) (Japan).png</marquee>
    <video>/home/pi/RetroPie/medias/msx2/logos/Gradius 3 - The Eve of Destruction (Cart) (Japan).mp4</video>
    <rating>0.9</rating>
    <releasedate>19880101T000000</releasedate>
    <developer>Konami</developer>
    <publisher>Konami</publisher>
    <genre>Shooter</genre>
    <players>2</players>
  </game>`

And add after <video> the new <thumbnail> TAG for the action/title shot ... but it's more work i know because you must also modify settings for this image options.

**Comment by gazpan** [comment]
Hi, thanks for the info and sorry for not getting back to you earlier.

I have a good idea about most of these problems so should be able to sort out quickly.

I did some work with system carousel to get custom collections working last weekend but at the same time making changes that should fix your initial problems. Although there were some fundamental changes that affected a lot of the system it was all mostly working except for 4 issues I didn't have time to finish off.

Since last 11 days though I've had a lot of pain with dental issues that affected my sleep so I haven't been working on WebtroPie, but I'm getting well now and have a couple of days off so hope to get back to it this weekend.

I'm aiming at sorting the above issues and the custom collections this weekend.

I'm looking forward to checking out your awesome theme!

**Comment by Darknior** [comment]
WOAW it's excellent everything you write!
If you finish all of this, Webtropie will still make a leap forward: p
Take good care of your teeth, it is important and it does not repel.
I intend to update my theme tonight with new systems and less bugs.
Thank you

**Comment by Darknior** [comment]
Hello, me again :p 
I forgot to write you i have a bug with MEDIA on some games ...
I can read text bur images and video are not displayed :(
There are the games with % or some symbol in the name of the ROM like for exemple : 

`Shockman (USA) [T+Fre 1.0 by FlashPV 100%]`
or
`Bikkuriman World (Japan) [T+Fre 1.02 by Raph99 100%]`
Because it search the image with : 
`http://192.168.1.21/app/svr/medias/pcengine/box%20front/Bikkuriman%20World%20(Japan)%20[T+Fre%201.02%20by%20Raph99%20100%].jpg?1497092544`
And don't replace the **%** by **%25** like this : 
`http://192.168.1.21/app/svr/medias/pcengine/box%20front/Bikkuriman%20World%20(Japan)%20[T+Fre%201.02%20by%20Raph99%20100%25].jpg?1497092544`
And then it works fine :)

Thanks

**Comment by gazpan** [comment]
Hi, sorry it's been so long without progress, I've committed a small update that should help some of these issues.

**Comment by gazpan** [comment]
My gamelist's start with <?xml version="1.0"?> so, that should be working.
Before, empty gamelists would not show, they should now but only if the option "Show empty gamelists" is set to true, I think I originally added the option as my real RetroPie doesn't show systems that I don't have games for and I wanted to emulate that.

**Comment by gazpan** [comment]
<img width="1114" alt="screen shot 2018-03-11 at 19 21 37" src="https://user-images.githubusercontent.com/18727686/37257454-8b17d4fe-2561-11e8-9452-be7fb2646d4f.png">
Playstation image works!

**Comment by Darknior** [comment]
Hi, cool excellent thanks a lot :)
I will try that in some hours.

I never write PSX image is not working, before we can't see it because the skin was not finished. I add PSX to my skin last week and it's why now we can see it :)
I think the skin will be done this week for 120% of the Retropie systems. So many 100 hours of photoshop. You can see all my comit on my GIT ;)

The bug is on ScummVM or some other old computer list (where i must trick with a not empty gamelist.xml) ... and then i can always see the background image, it's the gray menu background image that is not displayed fine.

**Comment by Darknior** [comment]
Oups your last commit break me all :(
Now i have nothing visible :(
Only FAVORITES / LAST PLAYED / OPTIONS / ALL GAMES
I must revert to continue to use Webtropie :(

```
git reflog
git reset --hard 747acbc
```

I also try your first commit **238e1b1** but with it, i can list any games, all is empty.

Strange all was broken ... or maybe a bad test to know if i have or not a **gamelist.xml** ?

I also always use the "Show Empty systems" option from the beginning.
You're real, ES is not displaying a system if there is not one game!
But for theaming, it is cool if we can do it here.

**Comment by gazpan** [comment]
Hi, long time no speak, sorry for being quiet lately.

Could you upload your /etc/emulationstation/es_systems.cfg file please?

My dev version is working so need to find what is causing the problem, I did change it to use the paths from the config rather than assume roms are always in /home/pi/RetroPie/roms as I wanted it to behave more like ES and work in more situations - like installed from ubuntu for example.

**Comment by Darknior** [comment]
Hi, happy to read you again :)
I have some time to help you this week if you want :)

Here is my file : 
[es_systems.zip](https://github.com/gazpan/WebtroPie/files/1844417/es_systems.zip)
And you can try it with my IP.

The best way i think can be that i give you my system image, because i already share it with other members of my team. Like that we have all the same system, and we i update something it is for every one. But i must have your mail to give you access informations.

**Comment by gazpan** [comment]
Thanks that's great, I tried with an old es_systems file that you sent a long time ago but it worked fine so I'll try with the file above, or if I can't reproduce the error I'll try your IP if it's on the broken version, but yes a copy of your system image would be great too. My email is gpankhurst@hotmail.com.

**Comment by gazpan** [comment]
Hi, I've added an option to order the carousel by the system full name

https://youtu.be/vLmANJG8WIc

**Comment by Darknior** [comment]
Hi, your new COMIT works fine for the SYSTEM list, so excellent, and the order works fine too :)
But :

- I can see some systems i've comment in my es_systems.cfg ? Like fba or mame-mame4all & mame-libretro that have the same full name.
- The game counter always return zero
- All my gamelist are empty and the skin not loading fine on empty list.

With all these comit and revert i really don't know what else you have try to add or correct ... and we don't have a beautifull list of all the bugs i report to you, i must take time to list them if possible.

- One that not help me to skin is that you don't recognise the DEFAULT tag, to show an image if there is no PATH or if path image is not working.

Thanks

**Comment by Darknior** [comment]
- With your new commit i also lost some systems ... like on your video we can't the 3 AMIGA systems.

**Comment by gazpan** [comment]
Hi, I've fixed the issue with % in media filenames.

Are all issues here ok now do you think ?

**Comment by gazpan** [comment]
> One that not help me to skin is that you don't recognise the DEFAULT tag, to show an image if there is no PATH or if path image is not working.

I've changed it so that if a game has no image or the image is missing then the default image will show if it is defined for the md_image or md_marquee elements.

However, I've a feeling that you mean images for the system carousel, I see that you have default tags in your theme and it makes sense to me that if the current system has no theme or if an image as a variable that evaluates to something that doesn't exist then you might want to default an image for the controller or logo or background, is this what you mean?, is this something new in ES? - I did not see it in the es themes documentation

https://github.com/RetroPie/EmulationStation/blob/master/THEMES.md

... and the only use of default in other themes seems to be for the md_video element.

Having said that the documentation isn't that clear either, it doesn't say that it's just for the md_image or md_marquee element and if it's for any other image which just becomes visible when there is no game image then I would have expected it to be boolean instead of a path.

**Comment by Darknior** [comment]
For my part if i understand fine, and i verify it with real ES, all images and videos have **DEFAULT** image.
It's really cool for me, i use it for my **multi lang** theme project.

- I don't use it for **cover** or **logo** for the moment, and for video i show **THUMBNAIL**  [issue](https://github.com/gazpan/WebtroPie/issues/42) now supported.
- I use DEFAULT image for SYSTEM LOGO or SYSTEM IMAGE, SYS DESCRIPTION, SYS INFO to show US version if the user choose a lang not supported yet. For exemple all is in US, and FRench, near in SPasnish, but in JPanaese i only have photo and logo, no text for the moment, i show US to repalce with default value.
- In Caroussel it is a bug i report you, i don't use DEFAULT image but default TEXT !
Like that if no logo, i write with text the name of the system and it works really fine. If i rememeber fine you don't write fine the name with the good font size.

```
			<!-- To replace default image LOGO by default -->
			<!-- No declare System LOGO here -->
			<text name="logoText">
				<origin>0 0</origin>
				<pos>0.5 0.5</pos>
				<size>0.2005 0.0959</size>
				<fontSize>0.05</fontSize>
				<fontPath>./_art/Roboto-Medium.ttf</fontPath>
				<alignment>center</alignment>
				<forceUppercase>true</forceUppercase>
				<color>${logoColor}</color>
			</text>
```

**Comment by Darknior** [comment]
- Excellent thanks for the % it works fine :)
- Now i can also see all my systems and all my gamelist fine :)
You forgot one little bug with the skin.
These systems you show now, ScummVM, x68000, MSX1 etc ... when we enter to the gamelist, the skin not loading fine.
I have put some screenshot before on the top of the issue ;

https://user-images.githubusercontent.com/3703317/36805704-6915c222-1cbe-11e8-9075-7c1c73aed8f1.jpg
https://user-images.githubusercontent.com/3703317/36805767-8a08e7ac-1cbe-11e8-83ed-d3c8edaaef98.jpg
working fine on real ES : 
https://user-images.githubusercontent.com/3703317/36807178-87b13f32-1cc2-11e8-9f61-2ffe612cfc70.jpg

I don't know why you load the background, now with the good color and transparency, but you don't load my overlay that write info text, the gamelist background and the games names, the video background ...
And if i use the LEFT ARROW to move from ScummVM to SEGA 32x that working fine, and come back to ScummVM, the skin is always not loaded fine, but i can see the games in gamelist.xml
You can try it on my PI, we can't also see the game informations when we select it.

If i remember fine, i don't verify again you have already fixed : 

- The ORDER of TAG when ADD or MODIFY an game entry?
- REMOVE the <INDEX> tag

**Comment by gazpan** [comment]
Hi,

This confused me too!

I think that if you have view style set to 'Automatic' and when there is no video, or image then the view is being set to 'basic' or 'detailed'. If you set the view style always to 'video' then it will look like RetroPie (if you have retropie view style set to '
<img width="301" alt="video_view" src="https://user-images.githubusercontent.com/18727686/38259981-551f76a4-375e-11e8-9502-94c108badd36.png">
video' too).

**Comment by Darknior** [comment]
Ho my god, you are right, sorry :p 
It works fine for :) 
I also try to rename my systems <name> and it works fine.
I have open issues for other bugs, i think this one can be closed ;)
